# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-28 10:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Soru')),
                ('choice_one', models.CharField(max_length=255, verbose_name='Seçenek-1')),
                ('choice_two', models.CharField(max_length=255, verbose_name='Seçenek-2')),
                ('choice_three', models.CharField(max_length=255, verbose_name='Seçenek-3')),
                ('choice_four', models.CharField(max_length=255, verbose_name='Seçenek-4')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election.Survey', verbose_name='Araştırma')),
            ],
            options={
                'verbose_name': 'Soru',
                'verbose_name_plural': 'Sorular',
            },
        ),
    ]
